version: "3.8"

services:
  database:
    container_name: postgres
    build: ./image/postgres
    restart: always
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "randompassword"
    ports:
      - 5432:5432