const sampleTestData = [
  {
    id: 1,
    image_url: "/admin/images/sample-thumnail/Rectangle-61.png",
    name: "Inutanuki - GORAKUBA!",
    ruby: "",
    category: "Highschool",
    amount: 1500,
    release_status: "公開中",
    sales_status: "販売中",
    release_date: "2023/05/14 13:24",
    sales_start_date: "2023/05/14 13:24",
    sales_end_date: "2023/05/14 13:24",
  },
  {
    id: 2,
    image_url: "/admin/images/sample-thumnail/Rectangle-58.png",
    name: "Pento - GORAKUBA!",
    ruby: "",
    category: "Highschool",
    amount: 1200,
    release_status: "公開中",
    sales_status: "販売終了",
    release_date: "2023/05/14 13:24",
    sales_start_date: "2023/05/14 13:24",
    sales_end_date: "2023/05/14 13:24",
  },
  {
    id: 3,
    image_url: "/admin/images/sample-thumnail/Rectangle-60.png",
    name: "Encho. - GORAKUBA! ",
    ruby: "",
    category: "Highschool",
    amount: 2000,
    release_status: "非公開",
    sales_status: "",
    release_date: "",
    sales_start_date: "",
    sales_end_date: "",
  },
  {
    id: 4,
    image_url: "/admin/images/sample-thumnail/Rectangle-59.png",
    name: "Tenri Kannagi 2023",
    ruby: "",
    category: "",
    amount: 2500,
    release_status: "予約公開",
    sales_status: "",
    release_date: "2023/05/14 13:24",
    sales_start_date: "2023/05/14 13:24",
    sales_end_date: "2023/05/14 13:24",
  },
  {
    id: 5,
    image_url: "/admin/images/sample-thumnail/Rectangle-61.png",
    name: "SAMPLEITEM1234",
    ruby: "",
    category: "",
    amount: 0,
    release_status: "下書き",
    sales_status: "",
    release_date: "",
    sales_start_date: "",
    sales_end_date: "",
  },
  {
    id: 6,
    image_url: "/admin/images/sample-thumnail/Rectangle-61.png",
    name: "SAMPLEITEM1235",
    ruby: "",
    category: "",
    amount: 0,
    release_status: "下書き",
    sales_status: "",
    release_date: "",
    sales_start_date: "",
    sales_end_date: "",
  },
  {
    id: 7,
    image_url: "/admin/images/sample-thumnail/Rectangle-61.png",
    name: "SAMPLEITEM1236",
    ruby: "",
    category: "",
    amount: 0,
    release_status: "下書き",
    sales_status: "",
    release_date: "",
    sales_start_date: "",
    sales_end_date: "",
  },
];

export function fetchSamples() {
  return sampleTestData;
}

export function fetchSampleItem(id) {
  const item = sampleTestData.find((sample) => sample.id == id);
  return item || null; // Return the found item or null if not found
}
