name: Deploy Journal Preview on Vercel

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
  
jobs:
  deploy-journal-preview:
    uses: ./.github/workflows/_deploy-vercel.yml
    with:
      ENV_NAME: "journal-preview"
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JOURNAL }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      NPM_RC_FOR_GSAP: ${{ secrets.NPM_RC_FOR_GSAP }}
