name: Build and Deploy Server
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Config Greensock and Install Dependency
        run: npm config set //npm.greensock.com/:_authToken=${{secrets.GREENSOCK_TOKEN}} && npm config set @gsap:registry=https://npm.greensock.com && ls && npm i
      - name: Build and Deploy
        run: npm i -g firebase-tools && cd apps && cd firebase && cd functions && npm i && npm run build && firebase deploy -P tobiratory-f6ae1 --only functions:native,functions:flowTxSend,functions:flowTxMonitor --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
