name: Deploy Journal Preview on Vercel

on: push

jobs:
  deploy-journal-preview:
    uses: ./.github/workflows/_deploy-vercel.yml
    with:
      ENV_NAME: "journal-preview"
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_JOURNAL }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
